version: '3'

services:
  https:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'registry.etdchain.net -> http://registry:5000, hub.registry.etdchain.net -> http://registry-ui:80'
      STAGE: 'production' # Don't use production until staging works
      CLIENT_MAX_BODY_SIZE: 0
    volumes:
      - ./https:/var/lib/https-portal

  registry:
    image: registry:2
    volumes:
      - ./auth:/auth
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_STORAGE=s3
      - REGISTRY_STORAGE_S3_ACCESSKEY=${REGISTRY_STORAGE_S3_ACCESSKEY}
      - REGISTRY_STORAGE_S3_SECRETKEY=${REGISTRY_STORAGE_S3_SECRETKEY}
      - REGISTRY_STORAGE_S3_BUCKET=${REGISTRY_STORAGE_S3_BUCKET}
      - REGISTRY_STORAGE_S3_REGIONENDPOINT=${REGISTRY_STORAGE_S3_REGIONENDPOINT}
      - REGISTRY_STORAGE_S3_REGION=${REGISTRY_STORAGE_S3_REGION}
      - REGISTRY_STORAGE_S3_ROOTDIRECTORY=etd-registry
      - REGISTRY_MIDDLEWARE_STORAGE_OPTIONS_BASEURL=${REGISTRY_MIDDLEWARE_STORAGE_OPTIONS_BASEURL}
    ports:
      - 5001:5000
    restart: always
  
  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    depends_on:
      - registry
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000