version: '3'

services:
  registry:
    image: registry:2
    volumes:
      - ./images:/var/lib/registry
      - ./auth:/auth
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    ports:
      - 5001:5000
    restart: always
  
  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    depends_on:
      - registry
    ports:
      - 8080:80
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000